### ISSUE TITLE
[Minor Issue] Items stop automatically stacking (Fabric 1.17)

### ISSUE THREAD

**Issue by Desempregago** [Dunkmania101/SpatialHarvesters#49] opened 2021-08-12 21:54 UTC
[Video](https://streamable.com/w2mbyk)
This behavior stops as soon as I disable Spatial Harvesters

Minecraft 1.17.1
Spatial Harvesters for Fabric - v0.11.12a

**Comment by TheRealM18** [comment] 2021-08-16 10:24
This is an issue that goes beyond just the machines too. it can effect animal pickups too.

this is a major issue in my books.

**Comment by Dunkmania101** [comment] 2021-08-16 20:58
It's because the items have different data on them, which is normal in Minecraft. As for the Mob Keys not stacking, if they did stack, that would break them completely. Imagine you bound one to a mob, then took another one and bound it to a different mob and then threw one and picked it up again, and they merged. How would that work?

I suppose it can be annoying, but it's not a bug and is normal Minecraft behavior, so I'll close this.

**Closed as completed by Dunkmania101** 2021-08-16 20:58 UTC

**Comment by TheRealM18** [comment] 2021-08-18 19:51
This issue applies to both ores from the harvesters, and things link killing sheep, and have the meat only stack to 2.  This is a bug with your mod, as it will show up with only your mod in.
