### ISSUE TITLE
[Major issue] Item Stacking

### ISSUE THREAD

**Issue by TheRealM18** [Dunkmania101/SpatialHarvesters#50] opened 2021-08-18 19:56 UTC
If you kill 5 "minecraft:white_sheep" you will end up with 5-10 different stacks of 1 - 2 items in each.  This is probably with the same issue you have with the harvesters.  if you have 10 iron or come up, it every few will generate multiple stacks.  This is your mod, as I have had it by itself, and still will do it.

the temp fix i have for the harvesters was to use a hopper, instead of straight to a storage unit.

By the way, this is Fabric issue, not sure if it is on forge too.

**Comment by Dunkmania101** [comment] 2021-08-19 21:28
I'm not sure if you're saying this is the same issue as #49, but I think it is different and it does sound like a real problem.
Just to clarify, #49 wasn't an issue, it just looked like one but is actually normal Minecraft stacking logic.
I'm not entirely sure I've correctly understood what you're reporting as I can interpret it in two different ways: The mob harvesters are outputting excessive numbers of items or actually killing entities by hand is giving excessive drops. Is it one of those?
I'll look at my code and see if I can figure it out myself too.

**Comment by Dunkmania101** [comment] 2021-08-19 21:47
Wait, you said you fixed it by using a hopper. That makes me think that it isn't actually this mod as the harvesters don't have inventories, they only send items to adjacent blocks that do, meaning that the issue didn't happen when a different inventory was used. What did you use other than a vanilla hopper? Did you try a vanilla chest or barrel or something like that?

**Comment by Dunkmania101** [comment] 2021-08-19 22:06
I did some testing and couldn't reproduce what I think I understand you described.
You might have meant something else though, so I'll wait to close this until you respond.

**Comment by TheRealM18** [comment] 2021-08-21 11:06
The issue is not just with the harvesters of the ores, it also affects the killing of some mobs in survival... if you do not use hoppers it will do weird stacking issues.  I know for a fact that the meta data, and nbt data is correct, because you can restack them afterwards and they will work fine.  The issue is that the stacking is coming from your mod, I have had to temporally remove it from the pack, as it was causing too much issues.  when i removed it, the issues with the pickup inventory went away... so i know for a fact it was your mod.

**Comment by DudeRush666** [comment] 2021-08-25 20:35
I can confirm the stacking issues for the following mob dropped items when mobs are killed, Arrows, Wool, Tropical Fish, Bones, Rotton Flesh, Cobwebs. I have done extensive testing and can also confirm that it is not a Meta or ID issue as I have also tested for that, I have tested using just this mod on its own and also with a tons of mods and this only happens when this mod is included in the mod folder. I hope this problem can be fixed because I am excited to use this mod more than most mods out there. To reiterate the problem is either the items don't stack at all and have to be manually stacked or they stack in random numbers before creating a different stack. I Am Using Fabric 1.17.1

**Comment by Dunkmania101** [comment] 2021-11-05 23:47
I just noticed this is still open. I'm pretty sure I managed to fix it in version 0.11.12c, so I'll close it now. Feel free to reopen if it turns out my fix didn't work. For anyone who's curious, the problem was that I calling ItemStack.getNbt instead of ItemStack.writeNbt, so it was trying to recreate the drops based on the NBT data that was saved to them instead of their full representation. Reading over that, it seems like it shouldn't have produced any drops at all, but I guess we'll see what happens.

**Closed as completed by Dunkmania101** 2021-11-05 23:47 UTC
