### ISSUE TITLE
[FABRIC 1.17.1] Which energy cables are supported?

### ISSUE THREAD

**Issue by MSandro** [Dunkmania101/SpatialHarvesters#55] opened 2022-01-18 10:21 UTC
Hello, I tried every energy mod in my Modpack.
* Tech Reborn
* Industrial Revolution
* Modern Industrialization

but no energy cable connects to an Harvester Block.

MC 1.17.1
Fabric Loader 0.12.12
Fabric API 0.46.0
spatialharvesters_Fabric_1.17.x-0.11.12d.jar

**Comment by Dunkmania101** [comment] 2022-01-19 16:43
Anything using the Reborn energy API is supposed to work. They redid it recently and I suspect they didn't update the 1.17.1 version of Tech Reborn based on this issue. Maybe I could get around this by releasing an alternative jar for 1.17.1 that uses the old version but is otherwise identical.

**Comment by Cataratas** [comment] 2022-01-20 16:42
1.18.1 also has the same issue.

**Comment by mnsnownutt** [comment] 2022-01-21 13:44
> 1.18.1 also has the same issue.

Confirm.  I am trying the Benchmark II modpack and nothing works.  Went into a creative world to test and only heat generators work.  Tried power from Tech Reborn, Modern Industrialization, Industrial Revolution and Extra Generators and none of them will connect/work.

**Comment by Dunkmania101** [comment] 2022-01-23 02:10
It turns out I just forgot to register the tile entities using the new API. Thanks to TheVikingShip on the project's Discord for finding the problem!

**Comment by Dunkmania101** [comment] 2022-01-23 18:27
I just released 0.11.13 which should fix the problem, so I'll close this. Please reopen if it doesn't work!

**Comment by JustAnOkapi** [comment] 2022-01-23 20:45
The fix does not work for me
on 1.18.1 with v0.11.13
![image](https://user-images.githubusercontent.com/39418801/150697364-863b2b42-7518-4397-a90a-1dc6f99d492a.png)

**Comment by JustAnOkapi** [comment] 2022-01-23 20:46
![image](https://user-images.githubusercontent.com/39418801/150697364-863b2b42-7518-4397-a90a-1dc6f99d492a.png)

**Comment by Cataratas** [comment] 2022-01-23 21:15
Just updated to v0.11.13a, still not working for me.

**Comment by JustAnOkapi** [comment] 2022-01-23 21:50
@Dunkmania101 this should be reopened

**Comment by Dunkmania101** [comment] 2022-01-23 23:48
Gah! Sorry about this, I'll keep looking.

**Comment by Dunkmania101** [comment] 2022-01-23 23:59
I think the fix in 0.11.13 was on the right track but wasn't completely correct. Specifically, it was testing the wrong value for whether the block entity being registered should be registered as an energy handler. I've fixed that and the cables do seem to connect now in 0.11.13b. Thanks again to TheVikingShip for finding the root cause!

**Closed as completed by Dunkmania101** 2022-01-23 23:59 UTC

**Comment by JustAnOkapi** [comment] 2022-01-24 00:52
The issue is fixed in the last update v0.11.13b on 1.18.1

![image](https://user-images.githubusercontent.com/39418801/150705747-3ede4415-4854-4d02-b745-fb7623e060ef.png)

**Comment by 0gp** [comment] 2022-01-24 21:40
When will the 1.17.1 Fix be released?

**Comment by JustAnOkapi** [comment] 2022-01-24 21:43
> When will the 1.17.1 Fix be released?

I think it should already be out as v0.11.13b

**Comment by MSandro** [comment] 2022-01-26 13:34
spatialharvesters_Fabric_1.18.x-0.11.13b.jar is not compatible with MC **1.17.1**!
I can not find any 0.11.13 release for 1.17.1 on CurseForge :(

**Comment by Dunkmania101** [comment] 2022-01-26 13:50
I only released it for 1.18.x, not expecting anyone to care about 1.17.x. I'll do that one, too. It shouldn't be that hard, since the only real differences between them are which game version they get compiled for.

**Comment by MSandro** [comment] 2022-05-04 05:20
any news here? this bug is still not fixed for 1.17.1!
