### ISSUE TITLE
[Fabric] Respect all Inventories

### ISSUE THREAD

**Issue by 5cript** [Dunkmania101/SpatialHarvesters#51] opened 2021-11-09 20:33 UTC
Is it possible to allow "all" inventories for the harvester?
I thought the mod would not work, but I was using an iron chest not a vanilla chest and using that worked.

**Comment by Dunkmania101** [comment] 2021-11-09 20:37
Hmm, strange, it should have worked. Was it a trapped chest and, if so, was it open while you waited? All of the machines turn off when powered by redstone, so maybe that's what happened. I don't think I've ever tested the Fabric version with vanilla chests, only with vanilla barrels, so it could actually not be working. I'll check and see if I can reproduce this.

**Comment by 5cript** [comment] 2021-11-09 20:39
The mod i used this with was "Expanded Storage" Iron Chest. I let it sit several days and thought maybe its mega slow, but then I used a vanilla chest and all was working immediately.
Might be an issue with this chest mod explicitly.

**Comment by Dunkmania101** [comment] 2021-11-09 23:10
It looks like, at least as far as I can tell, the block entities from that mod don't implement the Inventory interface. I don't think there's anything I can do apart from adding specific support, which I'd rather avoid so I don't bog down the mod with  nonstandard per-case stuff that shouldn't be needed in the first place, since that interface is there for a reason. I'm pretty sure there's an official Fabric port of Iron Chests, maybe those would work instead.

**Comment by Dunkmania101** [comment] 2021-11-09 23:12
I'll close this, since it doesn't seem to be an issue on this mod's end.

**Closed as completed by Dunkmania101** 2021-11-09 23:12 UTC
