### ISSUE TITLE
Iron Harvester caused my server to crash

### ISSUE THREAD

**Issue by themonsterstorm** [Dunkmania101/SpatialHarvesters#2] opened 2020-08-16 08:19 UTC
As soon as I hooked up power to the harvester my server crashed and I had to remove the mod to even get back in the server.
[crash-2020-08-16_02.59.00-server.txt](https://github.com/Dunkmania101/SpatialHarvesters/files/5080254/crash-2020-08-16_02.59.00-server.txt)

**Comment by Dunkmania101** [comment] 2020-08-16 18:14
I think it may have been caused by the way I was doing the item output. I changed it to work the same way as a hopper, it'll be out soon.

**Comment by Dunkmania101** [comment] 2020-08-16 19:15
I'm closing the issue for now as it should be fixed in V0.1.4 (1.15.2) and V0.1.5 (1.16.1).
If it still doesn't work, please let me know!

**Closed as completed by Dunkmania101** 2020-08-16 19:15 UTC

**Comment by Dunkmania101** [comment] 2020-08-17 11:48
Actually, that fix may not have been a fix. I was looking at the crash report again and I think it was actually how I was getting the ItemStack to put in the chest. I'll revert back to the old output system since people were having issues with it and I'll add a fix the actual problem. Thanks!
